version: '2.0'

services:
  mongo: 
    image: mongo
    ports:
      - 27017:27018
  redis:
    image: redis
    ports:
      - 6379:6379
  maildev:
    image: djfarrelly/maildev
    ports: 
      - 1080:80 
      - 1025:25